name: linter

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - product
      - build
      - 'feature/*'

jobs:
  linter-check:
    runs-on: ubuntu-latest
    env:
      PY_SCRIPT_PATH: './scripts/wrs_algorithm'
    steps:
      - name: checkout branch
        uses: actions/checkout@master
      - name: setup python 2
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'
      - name: setup linter
        run: pip install pylint pycodestyle
      - name: config file existence check
        run: ls ./pylintrc ./setup.cfg > /dev/null
      - name: pylint check
        run: pylint $PY_SCRIPT_PATH --rcfile=./pylintrc --disable=import-error || true
      - name: pycodestyle check
        run: pycodestyle $PY_SCRIPT_PATH
